AW--Implemented Index/Create/Edit Page for Rider Application from Member's View
ucsb-cs156-m23/proj-gauchoride-m23-9am-3 pull request #44
Opened 2023-08-25 10:07 UTC by Kanagawa-okiNamiUra

In this PR, I implemented Index/Create/EditPage for Rider Application from Member's View (in the nav bar "Apply to be a rider." I also added a placeholder nav bar for admin's view.

Notice that this PR does not address not the fourth issue in the instruction because the show page, where fields not disabled in the form should be read only. I could not figure out how to do that other than writing a new Table component, which could be demanding considering the time I had. For now, the show button in the table will lead to the edit page, which is very similar to what it is supposed to look like.

Running Instance at: https://gride-albert-dev.dokku-03.cs.ucsb.edu/

An implementation note is that we (who have both ROLE_ADMIN and ROLE_MEMBER) will only have ROLE_MEMBER when we open the Index page. This is achieved by creating a copy of currentUser and modify the copy for easier reuse of the table component. In reality, it would not be a problem for users and we admins are barely affected. A picture explanation is attached below.
![image](https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/assets/114945790/d1bca035-2202-486f-8cf7-322f1bc71049)
- Notice the Admin field disappeared when we are at the URL /apply/rider.
![image](https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/assets/114945790/ea40413d-b286-44d6-a0cd-af2f89ffd47d)
- When we are no longer in that page, we're admins again. (The admins field appears in the picture above)

Some more screenshots of the app:
![image](https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/assets/114945790/180f3ba5-ad27-49f1-b78f-fe406ba2b7cf)
![image](https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/assets/114945790/7a5089fa-e9cf-4569-93d7-c3c4c2ba5faf)

2023-08-25 12:42 UTC, Danny-You approved these changes, later dismissed
LGTM! Ready to be reviewed by TA / Instructor

2023-08-25 16:52 UTC, InariHimeko submitted a review, later dismissed
LGTM

2023-08-25 20:44 UTC, pconrad requested changes
I think I found a bug.   I could be mistaken. Can you take a look?

2023-08-25 20:44 UTC, pconrad commented on frontend/src/main/components/Nav/AppNavbar.js
> +                  <Nav.Link as={Link} to="/admin/applications/riders">Rider Applications</Nav.Link>
This page doesn't seem to have an  entry in `App.js`, so it doesn't seem to be accessible for the admins.

Is that intentional?  Did I overlook something? 

Or is this a bug that needs to be fixed?

2023-08-25 20:49 UTC, pconrad commented
I think I found a bug in this PR.  Can someone on the team take a look?

It doesn't have to be the original PR author.  Anyone can take a look at this and try to fix it (or explain why it's not a bug).

Specifically, if you look at App.js on this branch:

https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/blob/Albert-RiderApp_III/frontend/src/App.js

There is no mapping for the route /admin/applications/riders

However, the menu option "Rider Applications" in the Navbar links to that URL, which is "not found".

<img width="866" alt="image" src="https://github.com/ucsb-cs156-m23/proj-gauchoride-m23-9am-3/assets/1119017/319667e9-6db1-4f9a-93e2-0828bb928318">

2023-08-25 21:15 UTC, Kanagawa-okiNamiUra commented
Thanks for pointing that out. I  will implement the Index Page for Rider Application in the next PR.

2023-08-27 01:55 UTC, lawrencewang30 approved these changes, later dismissed
Went on dokku instance and saw that the bug is now fixed. All other options are working as expected. Can merge to main whenever possible

2023-08-27 03:46 UTC, pconrad requested changes
ACK!  Timers in tests are a big no no.

I've outlined what is likely the proper way to do this below.

2023-08-27 03:46 UTC, pconrad commented on frontend/src/tests/pages/RiderApplication/RiderApplicationIndexPageMember.test.js
> +
NO!  This is not how you do it.  This makes what we call a "flaky test", one that sometimes works and sometimes doesn't.    

Resist the temptation to solve race conditions in tests with timers.

Here's probably what It should be:

```suggestion

await waitFor( ()=> {
 expect(getByTestId(`${testId}-cell-row-2-col-status`)).toHaveTextContent("pending");
            }
```

2023-08-27 03:46 UTC, pconrad commented on frontend/src/tests/pages/RiderApplication/RiderApplicationIndexPageMember.test.js
> +    });
NO!  see fix below

2023-08-27 18:11 UTC, lawrencewang30 approved these changes
Saw that the appropriate changes were made to the test files and controller file. Dokku instance still working as expected, can merge to main whenever possible

2023-08-27 20:15 UTC, pconrad approved these changes
LGTM!

2023-08-27 20:15 UTC, merged